apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: conector-copilot-zabbix
  namespace: conector-copilot-zabbix
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: conector-copilot-zabbix
